import os
import logging
import torch
import numpy as np
from PIL import Image
from transformers import CLIPProcessor, CLIPModel
from config import Config

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Singletons to store model and processor instances loaded only once
_model = None
_processor = None

def get_clip_resources():
    """Initializes and returns the CLIP Model and Processor singletons."""
    global _model, _processor
    if _model is None or _processor is None:
        try:
            logger.info(f"Initializing CLIP model '{Config.CLIP_MODEL_NAME}' on device '{Config.DEVICE}'...")
            try:
                # Attempt to load from local cache first to bypass potential SSL / network blockages
                _processor = CLIPProcessor.from_pretrained(Config.CLIP_MODEL_NAME, local_files_only=True)
                _model = CLIPModel.from_pretrained(Config.CLIP_MODEL_NAME, local_files_only=True).to(Config.DEVICE)
            except Exception as cache_err:
                logger.info(f"Local cache load failed or missing ({cache_err}). Fetching from Hugging Face...")
                _processor = CLIPProcessor.from_pretrained(Config.CLIP_MODEL_NAME)
                _model = CLIPModel.from_pretrained(Config.CLIP_MODEL_NAME).to(Config.DEVICE)
            
            _model.eval()  # Set model to evaluation mode to disable dropout/batchnorm updates
            logger.info("CLIP model and processor initialized successfully.")
        except Exception as e:
            logger.error(f"Failed to load CLIP model and processor components: {e}")
            raise e
    return _model, _processor


def get_text_embedding(text: str) -> list:
    """Generates a normalized embedding vector for the provided text query.
    
    Args:
        text (str): Input text query.
        
    Returns:
        list: Normalized 512-dimensional float list.
    """
    if not text or not isinstance(text, str):
        logger.warning("Empty or invalid text passed for embedding generation.")
        return []
    
    model, processor = get_clip_resources()
    try:
        inputs = processor(text=[text], return_tensors="pt", padding=True).to(Config.DEVICE)
        with torch.no_grad():
            text_features = model.get_text_features(**inputs)
            # L2 normalization to project embeddings onto hypersphere
            text_features = text_features / text_features.norm(dim=-1, keepdim=True)
            embedding = text_features[0].cpu().numpy().tolist()
            return embedding
    except Exception as e:
        logger.error(f"Error generating text embedding: {e}")
        raise e

def get_image_embedding(image_input) -> list:
    """Generates a normalized embedding vector for the provided image input.
    
    Args:
        image_input: Can be a file path (str/os.PathLike), a PIL Image object, or a file-like stream.
        
    Returns:
        list: Normalized 512-dimensional float list.
    """
    if image_input is None:
        logger.warning("No image input passed for embedding generation.")
        return []

    model, processor = get_clip_resources()
    try:
        # Reset file pointer if file-like/stream object to ensure we read from start
        if hasattr(image_input, 'seek'):
            try:
                image_input.seek(0)
            except Exception as seek_err:
                logger.warning(f"Unable to seek image_input stream: {seek_err}")

        # Load and convert image to RGB
        if isinstance(image_input, (str, os.PathLike)):
            image = Image.open(image_input).convert("RGB")
        elif isinstance(image_input, Image.Image):
            image = image_input.convert("RGB")
        else:
            # Fallback for file-like binary stream (e.g. Flask's FileStorage)
            image = Image.open(image_input).convert("RGB")

        inputs = processor(images=image, return_tensors="pt").to(Config.DEVICE)
        with torch.no_grad():
            image_features = model.get_image_features(**inputs)
            # L2 normalization
            image_features = image_features / image_features.norm(dim=-1, keepdim=True)
            embedding = image_features[0].cpu().numpy().tolist()
            return embedding
    except Exception as e:
        logger.error(f"Error generating image embedding: {e}")
        raise e

def cosine_similarity(vec1: list, vec2: list) -> float:
    """Calculates cosine similarity between two 1D embedding vectors.
    
    Since vectors generated by get_text_embedding and get_image_embedding are already 
    L2-normalized, cosine similarity simplifies to a simple dot product.
    
    Args:
        vec1 (list): First embedding vector.
        vec2 (list): Second embedding vector.
        
    Returns:
        float: Cosine similarity score bounded between -1.0 and 1.0 (typically 0.0 to 1.0 for CLIP).
    """
    if not vec1 or not vec2:
        return 0.0
    
    a = np.array(vec1)
    b = np.array(vec2)
    
    dot_product = np.dot(a, b)
    norm_a = np.linalg.norm(a)
    norm_b = np.linalg.norm(b)
    
    if norm_a == 0 or norm_b == 0:
        return 0.0
        
    return float(dot_product / (norm_a * norm_b))

def find_top_matches(query_embedding: list, products: list, top_k: int = 10, query_text_embedding: list = None, query_text: str = "") -> list:
    """Compares a query embedding against a list of product embeddings and returns the top matches.
    
    Implements a hybrid search:
    - If a text query is present, it computes both:
      1. Text-to-Image similarity (user query text vs. product image embedding)
      2. Text-to-Text similarity (user query text vs. product metadata text embedding)
      They are weighted together (0.4 image, 0.6 text) to ensure high precision.
    - If an image query is present, it computes Image-to-Image similarity.
    - Applies keyword boosting for exact name/category/tag matches.
    - Calibrates raw cosine similarities to user-friendly percentage scores (0.0 to 1.0).
    
    Args:
        query_embedding (list): The normalized query representation (text/image/combined).
        products (list): A list of product dicts fetched from MongoDB.
        top_k (int): Number of top results to return.
        query_text_embedding (list): Optional. The raw text query embedding.
        query_text (str): Optional. The raw text query string.
        
    Returns:
        list: Top matching products containing similarity_score, sorted descending by score.
    """
    if not query_embedding or not products:
        return []
        
    matches = []
    q_vec = np.array(query_embedding)
    q_text_vec = np.array(query_text_embedding) if query_text_embedding else None
    
    for prod in products:
        prod_emb = prod.get("embedding")
        if not prod_emb:
            continue
            
        p_vec = np.array(prod_emb)
        
        # 1. Cosine similarity with product image embedding
        dot_image = np.dot(q_vec, p_vec)
        norm_q = np.linalg.norm(q_vec)
        norm_p = np.linalg.norm(p_vec)
        image_score = float(dot_image / (norm_q * norm_p)) if norm_q > 0 and norm_p > 0 else 0.0
        
        # 2. Cosine similarity with product text embedding (if available)
        text_score = 0.0
        prod_text_emb = prod.get("text_embedding")
        if prod_text_emb and q_text_vec is not None:
            pt_vec = np.array(prod_text_emb)
            dot_text = np.dot(q_text_vec, pt_vec)
            norm_qt = np.linalg.norm(q_text_vec)
            norm_pt = np.linalg.norm(pt_vec)
            text_score = float(dot_text / (norm_qt * norm_pt)) if norm_qt > 0 and norm_pt > 0 else 0.0
            
        # 3. Hybrid scoring
        if prod_text_emb and q_text_vec is not None:
            # High weight on text-to-text to ensure exact product names and categories match perfectly
            base_score = 0.4 * image_score + 0.6 * text_score
        else:
            base_score = image_score
            
        # 4. Keyword Boosting
        boost = 0.0
        if query_text:
            query_text_clean = query_text.lower().strip()
            prod_name = prod.get("name", "").lower()
            prod_cat = prod.get("category", "").lower()
            prod_tags = [t.lower() for t in prod.get("tags", [])]
            
            # Exact name match
            if query_text_clean == prod_name:
                boost += 0.35
            # Substring name match or word overlap
            elif query_text_clean in prod_name:
                boost += 0.20
            else:
                query_words = set(query_text_clean.split())
                name_words = set(prod_name.split())
                name_intersection = query_words.intersection(name_words)
                if name_intersection:
                    boost += 0.15 * (len(name_intersection) / len(query_words))
            
            # Category match
            if query_text_clean in prod_cat or prod_cat in query_text_clean:
                boost += 0.10
            else:
                query_words = set(query_text_clean.split())
                cat_words = set(prod_cat.split())
                if query_words.intersection(cat_words):
                    boost += 0.05
                    
            # Tags match
            query_words = set(query_text_clean.split())
            if query_words.intersection(set(prod_tags)):
                boost += 0.05
                
        final_score = base_score + boost
        
        # 5. Calibration to user-friendly percentage (0.0 to 1.0)
        if query_text:
            if boost > 0:
                # Scaled score with keyword boost: guarantee high range [0.70, 1.00]
                calibrated_score = 0.70 + (base_score * 0.15) + boost
            else:
                # Pure semantic text-to-image: scale [0.15, 0.35] -> [0.45, 0.85]
                norm_score = (final_score - 0.15) / (0.35 - 0.15)
                calibrated_score = 0.45 + np.clip(norm_score, 0.0, 1.0) * 0.40
        else:
            # Pure image-to-image or combined search: scale [0.40, 0.90] -> [0.50, 0.98]
            norm_score = (final_score - 0.40) / (0.90 - 0.40)
            calibrated_score = 0.50 + np.clip(norm_score, 0.0, 1.0) * 0.48
            
        calibrated_score = float(np.clip(calibrated_score, 0.0, 1.0))
        
        # Shallow copy to format product dict for client presentation
        prod_copy = prod.copy()
        prod_copy["similarity_score"] = calibrated_score
        
        # Clean up database-specific and heavy fields for UI transmission
        if "embedding" in prod_copy:
            del prod_copy["embedding"]
        if "text_embedding" in prod_copy:
            del prod_copy["text_embedding"]
        if "_id" in prod_copy:
            prod_copy["_id"] = str(prod_copy["_id"])
            
        matches.append(prod_copy)
        
    # Sort matches by similarity score in descending order
    matches.sort(key=lambda x: x["similarity_score"], reverse=True)
    return matches[:top_k]
